services:
  app: 
    image: node:25
    volumes:
      - ./code:/app
    ports:
      - 3000:3000 #port de l'api 
      - 5173:5173 #port de react
      - 5500:5500 #port de live server
    tty: true
    restart: always
    working_dir: /app

 
  mysql:
    image: mysql:9.5
    ports: 
      - 3306:3306
    volumes:
      - ./code/mysql:/app
      - ./mysql-data:/var/lib/mysql
    working_dir: /app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  mongodb:
    image: mongo:8.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: root 
    ports:
      - 27017:27017
    volumes:
      - ./code/mongodb:/app
      - ./mongodb-data:/etc/mongo/
    working_dir: /app